<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GestorDeEventos.Domain\GestorDeEventos.Domain.csproj" />
    <ProjectReference Include="..\GestorDeEventos.Infrastructure\GestorDeEventos.Infrastructure.csproj" />
  </ItemGroup>

</Project>
